# Generated by Django 2.2.5 on 2020-02-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolErp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_url', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('admin_username', models.CharField(max_length=100)),
                ('admin_password', models.CharField(max_length=100)),
            ],
        ),
    ]
